### ISSUE TITLE
Eager execution function cannot be Keras symbolic tensors

### ISSUE THREAD

**Issue by dhyeythumar** [ChintanTrivedi/rl-bot-football#2]
Hi, @ChintanTrivedi I am using the modified version of your code to train the environment created using the Unity engine.

[I have modified the code to handle this].
Action space = Continuous
Observation space = Vectorized

TensorFlow version =  2.3.0
Python version =  3.8.3

**I think the error is introduced due to the custom loss function call. [Tensor is passed to the loss function so eager execution is giving error]**

So while I am trying to fit the model to the collected data, I am getting the following errors.
So, please can you tell me what am I doing wrong?

```bash
Epoch 1/8
Traceback (most recent call last):
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: old_prediction:0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "temp.py", line 259, in <module>
    agent.train()
  File "temp.py", line 228, in train
    actor_loss = self.actor.fit(
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\eager\def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\eager\function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\eager\function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\eager\function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\eager\function.py", line 545, in call
    outputs = execute.execute(
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\eager\execute.py", line 72, in quick_execute
    raise core._SymbolicException(
tensorflow.python.eager.core._SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'old_prediction:0' shape=(None, 2) dtype=float32>, <tf.Tensor 'advantage:0' shape=(None, 1) dtype=float32>, <tf.Tensor 'reward:0' shape=(None, 1) dtype=float32>, <tf.Tensor 'value:0' shape=(None, 1) dtype=float32>]
```

Here is the code which is calling the .fit() method to the model:

```python
while not target_reached and iters < max_iters:
            states = []
            actions = []
            old_predictions = []
            rewards = []
            values = []
            masks = []
            state = None
            self.env.reset()
            step_result = self.env.get_steps(self.behavior_name)
            state = step_result[0].obs[0]  # observation

            for itr in range(ppo_steps):
                #generate the actions using predict method on actor model.
                action, action_matrix, predicted_action = self.get_action(state, True) 

                q_value = self.critic.predict(state, steps=1)

                next_state, reward, done = self.step(action) # apply the actions to the env and returns the env response. 

                print('itr: ' + str(itr) + ', reward=' + str(reward) + ', q_val=' + str(q_value))
                mask = not done

                states.append(state)
                actions.append(action_matrix)
                old_predictions.append(predicted_action)
                rewards.append(reward)
                values.append(q_value)
                masks.append(mask)

                state = next_state
                if done:
                    self.env.reset()

            q_value = self.critic.predict(state, steps=1)
            values.append(q_value)
            returns, advantages = self.get_advantages(values, masks, rewards)
            
            # reshaping
            states = np.reshape(states, (len(states), self.state_dims))
            actions = np.reshape(actions, (len(actions), self.n_actions))
            old_predictions = np.reshape(old_predictions, (len(old_predictions), self.n_actions))

            rewards = np.reshape(rewards, (-1, 1))
            values = np.reshape(values, (len(values), 1))
            advantages = np.reshape(advantages, (len(advantages), 1))
            returns = np.reshape(returns, (len(returns), 1))

            actor_loss = self.actor.fit(
                [states, old_predictions, advantages, rewards, values[:-1]],
                [actions],
                verbose=True, shuffle=True, epochs=8,
                callbacks=[self.tensor_board]
            )
            critic_loss = self.critic.fit(
                [states], [returns],
                shuffle=True, epochs=8, verbose=True,
                callbacks=[self.tensor_board]
            )
```

**Comment by Dhyeythumar** [comment]
#27519
I found this relevant to this issue.

**Comment by Dhyeythumar** [comment]
https://github.com/tensorflow/tensorflow/issues/27519

**Comment by dhyeythumar** [comment]
I found these Tensorflow issues useful:

[Custom loss using intermediate tensorflow probability layer with Eager execution](https://github.com/tensorflow/tensorflow/issues/42825)

[TF 2.0 'Tensor' object has no attribute 'numpy' while using .numpy() although eager execution enabled by default](https://github.com/tensorflow/tensorflow/issues/27519)

[TF 2.0 Custom Metric 'Tensor' object has no attribute 'numpy'](https://github.com/tensorflow/tensorflow/issues/35393)

**Comment by gholmes829** [comment]
I'm having this same issue. Has anyone found a solution?

**Comment by dhyeythumar** [comment]
Hi @gholmes829, Till now I didn't find any solution despite filing an issue on Tensorflow's repo.
Here it is: [Custom loss function is not working](https://github.com/tensorflow/tensorflow/issues/43650)

_**I am not sure but I think this issue is occurring only on TensorFlow 2.x, So you can try TensorFlow 1.x.**_

**Comment by gholmes829** [comment]
@dhyeythumar Thank you so much for the reply and resources!

I'd really like to use TF2 and I may have found a potential workaround to do so. We should be able to make a basic class for the actor network implemented as low level TensorFlow model. This allows us to define a custom training method utilizing the gradient tape context https://www.tensorflow.org/tutorials/customization/custom_training_walkthrough.

This design would allow us to pass an arbitrary number of parameters to the loss function and call the loss and optimization functions explicitly. I will test this idea out and update with my results.

**Comment by dhyeythumar** [comment]
Yes this should also work, & I think this [**comment** ](https://github.com/tensorflow/tensorflow/issues/47311#issuecomment-824979138) might be helpful as well.

**Comment by NewComer00** [comment]
I found [this answer](https://stackoverflow.com/a/68275764) in stackoverflow. The "[add_loss](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer#methods_2)" method seems to solve my problem. 
Here is my code, and hope it can help :)
```py
def ppo_loss(y_true, y_pred, oldpolicy_probs, advantages, rewards, values):
    newpolicy_probs = y_pred
    ratio = K.exp(K.log(newpolicy_probs + 1e-10) - K.log(oldpolicy_probs + 1e-10))
    p1 = ratio * advantages
    p2 = K.clip(ratio, min_value=1 - clipping_val, max_value=1 + clipping_val) * advantages
    actor_loss = -K.mean(K.minimum(p1, p2))
    critic_loss = K.mean(K.square(rewards - values))
    total_loss = critic_discount * critic_loss + actor_loss - entropy_beta * K.mean(
        -(newpolicy_probs * K.log(newpolicy_probs + 1e-10)))
    return total_loss

def get_model_actor(input_dims, output_dims):
    state_input = Input(shape=input_dims)
    oldpolicy_probs = Input(shape=(1, output_dims,))
    advantages = Input(shape=(1, 1,))
    rewards = Input(shape=(1, 1,))
    values = Input(shape=(1, 1,))

    n_actions = output_dims
    feature_extractor = MobileNetV2(
        input_shape=(*MOBILENET_IMG_SIZE, 3),
        weights='imagenet', include_top=False)
    for layer in feature_extractor.layers:
        layer.trainable = False
    x = Flatten(name='flatten')(feature_extractor(state_input))
    x = Dense(1024, activation='relu', name='fc1')(x)
    out_actions = Dense(n_actions, activation='sigmoid')(x)
    model_actor = Model(
        inputs=[state_input, oldpolicy_probs, advantages, rewards, values],
        outputs=[out_actions])
    # ==================================================
    # ==================================================
    model_actor.add_loss(ppo_loss(
        y_true=None,
        y_pred=out_actions,
        oldpolicy_probs=oldpolicy_probs,
        advantages=advantages,
        rewards=rewards,
        values=values))
    model_actor.compile(optimizer=Adam(lr=1e-4))
    # ==================================================
    # ==================================================
    return model_actor
```
